path = "C:/Users/WilliamNash/Bactobio Dropbox/Baccuico/LAB Work/Lab Work - Will/Mass_spec_data/20240109_Set1and2mix_LM2/MZMine3_Filtering1/"
batch_name = "20240109_Set1and2mix_LM2"
MS_system = "Agilent"
peaklist = "peaklist.csv"
Bio_identifier = "Set"
Media_identifier = "dnadjslaj"
Blank_identifier = "Blank"
QC_identifier = "QC"
Blank_thresh = 10
FC_threshold = 10
RSD_threshold = 30
peak_height_threshold = 10000
bio_media_linkers = "NA"