path = "C:/Users/WilliamNash/Bactobio Dropbox/Baccuico/LAB Work/Lab Work - Will/Mass_spec_data/20230919_EON_batch_AM39/MZMine3_test/"
batch_name = "20230919_EON_batch_AM39"
MS_system = "Agilent"
peaklist = "peaklist.csv"
Bio_identifier = "A"
Blank_identifier = "Blank"
Media_identifier = "QC"
QC_identifier = "QC"
bio_media_linkers = "NA"
FC_threshold = 5
RSD_threshold = 30
peak_height_threshold = 10000
Blank_thresh = 10